export const WS_CONNECTION_START = 'WS_CONNECTION_START';
export const WS_SEND_MESSAGE = 'WS_SEND_MESSAGE';
export const WS_AUTH_CONNECTION_START = 'WS_AUTH_CONNECTION_START';
export const WS_AUTH_SEND_MESSAGE = 'WS_AUTH_SEND_MESSAGE';